apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gke-app
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/gke"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
